version: "3.1"

services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile-Backend
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mysql
      - rabbitmq
      - redis
      - elasticsearch
      - minio
    environment:
      ENV: ${ENV:-qa}

  frontend:
    build:
      context: ../
      dockerfile: Dockerfile-Frontend
    ports:
      - 4000:4000
    depends_on:
      - backend
      - minio
    environment:
      ENV: ${ENV:-qa}
