FROM openjdk:14-jdk-slim as builder
WORKDIR /app
COPY rakonto-backend .
RUN ./gradlew build

FROM openjdk:14-jdk-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg imagemagick
COPY --from=builder /app/build/libs/*.jar ./app.jar
EXPOSE 8080
CMD [ "sh", "-c", "java -jar -Dspring.profiles.active=${ENV} app.jar" ]
