FROM openjdk:14-jdk-slim as builder
WORKDIR /app
COPY rakonto-backend .
RUN ./gradlew build

FROM openjdk:14-jdk-slim
WORKDIR /app
COPY --from=builder /app/build/libs/webapp-0.0.1.jar ./webapp-0.0.1.jar
EXPOSE 8080
CMD [ "sh", "-c", "java -jar -Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6666 -Dspring.profiles.active=${ENV} webapp-0.0.1.jar" ]
