FROM node:17-alpine as build
WORKDIR /app
COPY rakonto-ui/package.json .
COPY rakonto-ui/yarn.lock .
RUN npx yarn install
COPY rakonto-ui .
RUN npx yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]
