version: "3.1"

services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile-Backend
    ports:
      - 8080:8080
      - 6666:6666
    volumes:
      - ~/rakonto-data/docker/binary:/app/uploads
    depends_on:
      - mysql
      - rabbitmq
      - redis
      - elasticsearch
    environment:
      ENV: ${ENV:-qa}

  frontend:
    build:
      context: ../
      dockerfile: Dockerfile-Frontend
    ports:
      - 4000:4000
    depends_on:
      - backend
    environment:
      ENV: ${ENV:-qa}
